"""faculty_multi_subject

Revision ID: 7c9e88997091
Revises: 7034de1caf68
Create Date: 2026-05-11 12:49:03.688610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c9e88997091'
down_revision: Union[str, None] = '7034de1caf68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('faculty_subjects_user_id_key', 'faculty_subjects', type_='unique')
    op.create_unique_constraint('uq_faculty_subject', 'faculty_subjects', ['user_id', 'subject'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_faculty_subject', 'faculty_subjects', type_='unique')
    op.create_unique_constraint('faculty_subjects_user_id_key', 'faculty_subjects', ['user_id'])
    # ### end Alembic commands ###
