"""faculty_section_per_subject

Revision ID: af1c704a4403
Revises: 7c9e88997091
Create Date: 2026-05-11 12:56:32.165043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1c704a4403'
down_revision: Union[str, None] = '7c9e88997091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Clear existing rows — schema change is breaking (subject is now required per slot)
    op.execute("DELETE FROM faculty_sections")
    op.drop_constraint('uq_faculty_branch_section', 'faculty_sections', type_='unique')
    op.add_column('faculty_sections', sa.Column('subject', sa.Enum('Maths', 'Chemistry', 'Physics', name='subjectname_enum'), nullable=False))
    op.create_unique_constraint('uq_faculty_section_subject', 'faculty_sections', ['branch_section_id', 'subject'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_faculty_section_subject', 'faculty_sections', type_='unique')
    op.create_unique_constraint('uq_faculty_branch_section', 'faculty_sections', ['user_id', 'branch_section_id'])
    op.drop_column('faculty_sections', 'subject')
    # ### end Alembic commands ###
